using DocHub.DataAccess;
using DocHub.Services.ViewModels;

namespace DocHub.Services.Tests;

/// <summary>
/// The pipeline end to end against real Postgres and real blob storage, with
/// only the embedding model faked — the seams between upload, extraction,
/// chunk storage and status are exactly where this can go wrong.
/// </summary>
[Collection(nameof(StackCollection))]
public sealed class IngestionPipelineTests(StackFixture fixture)
{
    private static UploadRequest Upload(string body, string fileName) =>
        new(StackFixture.FileOf(body), fileName, "text/markdown",
            System.Text.Encoding.UTF8.GetByteCount(body));

    private static string Unique(string name) => $"{name}-{Guid.NewGuid():N}"[..22];

    private const string Guide = """
        # Remote Access

        ## Connecting to the VPN

        All staff working outside the office must connect through the company VPN before
        reaching internal systems. Download the client from the IT portal and sign in with
        your usual network credentials.

        ## Multi-factor authentication

        Every remote session requires a second factor. We use time-based one-time passwords
        generated by the authenticator app on your phone. Hardware tokens are available for
        staff who cannot install the app.
        """;

    [Fact]
    public async Task Uploading_queues_the_document_rather_than_indexing_inline()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("Q")));

        var created = await scope.Documents.UploadAsync(folder.Id, Upload(Guide, "vpn.md"));

        // Embedding a document takes far longer than an upload should, so the
        // response must come back before any of it has happened.
        Assert.Equal("pending", created.Status);
        Assert.Contains(created.Id, scope.Queue.Queued);
    }

    [Fact]
    public async Task Ingestion_indexes_the_document_and_stores_its_chunks()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("I")));
        var created = await scope.Documents.UploadAsync(folder.Id, Upload(Guide, "vpn.md"));

        await scope.Ingestion.IngestAsync(created.Id);

        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("indexed", detail.Document.Status);
        Assert.Null(detail.Document.FailureReason);
        Assert.Equal(detail.Sections.Count, detail.Document.ChunkCount);
        Assert.NotEmpty(detail.Sections);

        // Markdown headings must survive all the way to the citation label.
        Assert.Contains(detail.Sections, section => section.Heading.Contains("Connecting"));
        Assert.Contains(detail.Sections, section => section.Heading.Contains("Multi-factor"));
    }

    [Fact]
    public async Task A_document_with_an_enormous_heading_still_indexes()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("H")));

        // A heading far longer than the section_ref column. This used to reach
        // Postgres unclamped and fail the insert with 22001, which failed the
        // whole document — on its label, with its content perfectly fine.
        var body = $"""
            # {new string('L', 900)}

            All staff working outside the office must connect through the company VPN before
            reaching internal systems. Download the client from the IT portal and sign in.
            """;

        var created = await scope.Documents.UploadAsync(folder.Id, Upload(body, "long.md"));
        await scope.Ingestion.IngestAsync(created.Id);

        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("indexed", detail.Document.Status);
        Assert.Null(detail.Document.FailureReason);

        // The label is shortened rather than dropped: a citation still says
        // which part of the document it came from.
        var heading = Assert.Single(detail.Sections).Heading;
        Assert.StartsWith("LLL", heading);
        Assert.Equal(DocHubDbContext.SectionRefMaxLength, heading.Length);
    }

    [Fact]
    public async Task Re_ingesting_replaces_chunks_instead_of_appending_them()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("R")));
        var created = await scope.Documents.UploadAsync(folder.Id, Upload(Guide, "vpn.md"));

        await scope.Ingestion.IngestAsync(created.Id);
        var first = (await scope.Documents.GetAsync(created.Id)).Sections.Count;

        // A retried job must be safe to run twice.
        await scope.Ingestion.IngestAsync(created.Id);
        var second = (await scope.Documents.GetAsync(created.Id)).Sections.Count;

        Assert.Equal(first, second);
    }

    [Fact]
    public async Task An_unsupported_file_type_fails_with_a_reason_naming_what_is_supported()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("U")));

        var created = await scope.Documents.UploadAsync(
            folder.Id,
            new UploadRequest(StackFixture.FileOf("binary"), "diagram.png", "image/png", 6));

        await scope.Ingestion.IngestAsync(created.Id);

        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("failed", detail.Document.Status);
        Assert.Contains(".png", detail.Document.FailureReason);
        Assert.Contains(".md", detail.Document.FailureReason);
        Assert.Empty(detail.Sections);
    }

    [Fact]
    public async Task A_file_with_no_extractable_text_fails_rather_than_indexing_nothing()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("E")));

        var created = await scope.Documents.UploadAsync(folder.Id, Upload("   \n  ", "empty.md"));

        await scope.Ingestion.IngestAsync(created.Id);

        var detail = await scope.Documents.GetAsync(created.Id);
        Assert.Equal("failed", detail.Document.Status);
        Assert.Contains("No text could be extracted", detail.Document.FailureReason);
    }

    [Fact]
    public async Task A_new_version_invalidates_the_old_chunks_and_requeues()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("V")));
        var created = await scope.Documents.UploadAsync(folder.Id, Upload(Guide, "vpn.md"));
        await scope.Ingestion.IngestAsync(created.Id);

        var updated = await scope.Documents.AddVersionAsync(
            created.Id, Upload("# Rewritten\n\nCompletely different content about printers.", "vpn.md"));

        // The stored chunks now describe content that is no longer current, so
        // the document must drop out of search until it is re-ingested.
        Assert.Equal("pending", updated.Status);
        Assert.Contains(created.Id, scope.Queue.Queued);

        await scope.Ingestion.IngestAsync(created.Id);
        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("indexed", detail.Document.Status);
        Assert.DoesNotContain(detail.Sections, section => section.Body.Contains("VPN"));
    }

    [Fact]
    public async Task Requeueing_clears_a_previous_failure()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("F")));
        var created = await scope.Documents.UploadAsync(
            folder.Id,
            new UploadRequest(StackFixture.FileOf("x"), "art.png", "image/png", 1));

        await scope.Ingestion.IngestAsync(created.Id);
        Assert.Equal("failed", (await scope.Documents.GetAsync(created.Id)).Document.Status);

        var requeued = await scope.Ingestion.RequeueAsync(created.Id);

        Assert.Equal("pending", requeued.Status);
        Assert.Null(requeued.FailureReason);
    }

    [Fact]
    public async Task Deleting_a_document_takes_its_chunks_with_it()
    {
        await using var scope = fixture.NewScope();
        var folder = await scope.Folders.CreateAsync(new CreateFolderRequest(null, Unique("D")));
        var created = await scope.Documents.UploadAsync(folder.Id, Upload(Guide, "vpn.md"));
        await scope.Ingestion.IngestAsync(created.Id);

        Assert.NotEmpty(await scope.Chunks.GetForDocumentAsync(created.Id));

        await scope.Documents.DeleteAsync(created.Id);

        // Otherwise deleted content stays answerable through search.
        Assert.Empty(await scope.Chunks.GetForDocumentAsync(created.Id));
    }
}
