using DocHub.DataAccess;
using DocHub.Services.ViewModels;

namespace DocHub.Services.Tests;

/// <summary>
/// The pipeline end to end against real Postgres, with the repository and the
/// embedding model faked — the seams between mirroring, extraction, chunk
/// storage and status are exactly where this can go wrong.
/// </summary>
[Collection(nameof(StackCollection))]
public sealed class IngestionPipelineTests(StackFixture fixture)
{
    private static string Unique(string name) => $"{name}-{Guid.NewGuid():N}"[..22];

    private const string Guide = """
        # Remote Access

        ## Connecting to the VPN

        All staff working outside the office must connect through the company VPN before
        reaching internal systems. Download the client from the IT portal and sign in with
        your usual network credentials.

        ## Multi-factor authentication

        Every remote session requires a second factor. We use time-based one-time passwords
        generated by the authenticator app on your phone. Hardware tokens are available for
        staff who cannot install the app.
        """;

    [Fact]
    public async Task Mirroring_queues_the_document_rather_than_indexing_inline()
    {
        await using var scope = fixture.NewScope();

        var created = await scope.PublishAsync($"{Unique("Q")}/vpn.md", Guide);

        // Embedding a repository's worth of documents takes minutes, so a sync
        // must come back before any of it has happened.
        Assert.Equal("pending", created.Status);
        Assert.Contains(created.Id, scope.Queue.Queued);
    }

    [Fact]
    public async Task Ingestion_indexes_the_document_and_stores_its_chunks()
    {
        await using var scope = fixture.NewScope();
        var created = await scope.PublishIndexedAsync($"{Unique("I")}/vpn.md", Guide);

        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("indexed", detail.Document.Status);
        Assert.Null(detail.Document.FailureReason);
        Assert.Equal(detail.Sections.Count, detail.Document.ChunkCount);
        Assert.NotEmpty(detail.Sections);

        // Markdown headings must survive all the way to the citation label.
        Assert.Contains(detail.Sections, section => section.Heading.Contains("Connecting"));
        Assert.Contains(detail.Sections, section => section.Heading.Contains("Multi-factor"));
    }

    [Fact]
    public async Task A_document_with_an_enormous_heading_still_indexes()
    {
        await using var scope = fixture.NewScope();
        // A heading far longer than the section_ref column. This used to reach
        // Postgres unclamped and fail the insert with 22001, which failed the
        // whole document — on its label, with its content perfectly fine.
        var body = $"""
            # {new string('L', 900)}

            All staff working outside the office must connect through the company VPN before
            reaching internal systems. Download the client from the IT portal and sign in.
            """;

        var created = await scope.PublishIndexedAsync($"{Unique("H")}/long.md", body);

        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("indexed", detail.Document.Status);
        Assert.Null(detail.Document.FailureReason);

        // The label is shortened rather than dropped: a citation still says
        // which part of the document it came from.
        var heading = Assert.Single(detail.Sections).Heading;
        Assert.StartsWith("LLL", heading);
        Assert.Equal(DocHubDbContext.SectionRefMaxLength, heading.Length);
    }

    [Fact]
    public async Task Re_ingesting_replaces_chunks_instead_of_appending_them()
    {
        await using var scope = fixture.NewScope();
        var created = await scope.PublishIndexedAsync($"{Unique("R")}/vpn.md", Guide);
        var first = (await scope.Documents.GetAsync(created.Id)).Sections.Count;

        // A retried job must be safe to run twice.
        await scope.Ingestion.IngestAsync(created.Id);
        var second = (await scope.Documents.GetAsync(created.Id)).Sections.Count;

        Assert.Equal(first, second);
    }

    [Fact]
    public async Task A_type_no_extractor_can_read_never_becomes_a_document_at_all()
    {
        await using var scope = fixture.NewScope();
        var directory = Unique("U");

        scope.Repository.Put($"{directory}/diagram.png", "binary");
        scope.Repository.Put($"{directory}/notes.md", Guide);
        await scope.Mirror.SyncAsync(actorId: null);

        var documents = await scope.Documents.QueryAsync(new DocumentQueryRequest { Take = 500 });

        // Under uploads this was a failed document, because a person had chosen
        // to upload it and deserved to be told why it was not searchable. A
        // repository chose nothing — it is simply full of files that are not
        // documentation — so a permanent "failed" row for each would be noise
        // that never clears.
        Assert.DoesNotContain(documents, document => document.FileName == "diagram.png");
        Assert.Contains(documents, document => document.FileName == "notes.md");
    }

    [Fact]
    public async Task A_file_with_no_extractable_text_fails_rather_than_indexing_nothing()
    {
        await using var scope = fixture.NewScope();
        var created = await scope.PublishIndexedAsync($"{Unique("E")}/empty.md", "   \n  ");

        var detail = await scope.Documents.GetAsync(created.Id);
        Assert.Equal("failed", detail.Document.Status);
        Assert.Contains("No text could be extracted", detail.Document.FailureReason);
    }

    [Fact]
    public async Task A_new_revision_invalidates_the_old_chunks_and_requeues()
    {
        await using var scope = fixture.NewScope();
        var path = $"{Unique("V")}/vpn.md";
        var created = await scope.PublishIndexedAsync(path, Guide);

        scope.Repository.Put(path, "# Rewritten\n\nCompletely different content about printers.");
        await scope.Mirror.SyncAsync(actorId: null);

        // The stored chunks now describe content the repository no longer has,
        // so the document must drop out of search until it is re-ingested.
        var updated = (await scope.Documents.GetAsync(created.Id)).Document;
        Assert.Equal("pending", updated.Status);
        Assert.Contains(created.Id, scope.Queue.Queued);

        await scope.Ingestion.IngestAsync(created.Id);
        var detail = await scope.Documents.GetAsync(created.Id);

        Assert.Equal("indexed", detail.Document.Status);
        Assert.DoesNotContain(detail.Sections, section => section.Body.Contains("VPN"));
    }

    [Fact]
    public async Task Requeueing_clears_a_previous_failure()
    {
        await using var scope = fixture.NewScope();
        var created = await scope.PublishIndexedAsync($"{Unique("F")}/blank.md", "   ");

        Assert.Equal("failed", (await scope.Documents.GetAsync(created.Id)).Document.Status);

        var requeued = await scope.Ingestion.RequeueAsync(created.Id);

        Assert.Equal("pending", requeued.Status);
        Assert.Null(requeued.FailureReason);
    }

    [Fact]
    public async Task A_file_that_leaves_the_repository_takes_its_chunks_with_it()
    {
        await using var scope = fixture.NewScope();
        var path = $"{Unique("D")}/vpn.md";
        var created = await scope.PublishIndexedAsync(path, Guide);

        Assert.NotEmpty(await scope.Chunks.GetForDocumentAsync(created.Id));

        scope.Repository.Remove(path);
        await scope.Mirror.SyncAsync(actorId: null);

        // Otherwise deleted content stays answerable through search.
        Assert.Empty(await scope.Chunks.GetForDocumentAsync(created.Id));
    }
}
