using NpgsqlTypes;
using Pgvector;

namespace DocHub.DataAccess.Entities;

/// <summary>
/// One retrievable passage of a document, produced by the ingestion pipeline.
///
/// This is the unit search and (from phase 3) the assistant actually work with
/// — never the whole document. Keeping <see cref="SectionRef"/> and
/// <see cref="Ordinal"/> alongside the text is what lets a citation point at
/// "page 4" rather than vaguely at the file.
/// </summary>
public class DocumentChunk
{
    public Guid Id { get; set; }

    public Guid DocumentId { get; set; }

    /// <summary>Position within the document, starting at 0.</summary>
    public int Ordinal { get; set; }

    public required string Text { get; set; }

    /// <summary>
    /// Human-readable location shown in a citation — "Page 4", "Slide 2",
    /// "## Local setup". Null when the format offers nothing better than the
    /// ordinal.
    /// </summary>
    public string? SectionRef { get; set; }

    /// <summary>Approximate token count, used to keep prompt budgets honest in phase 3.</summary>
    public int TokenCount { get; set; }

    /// <summary>
    /// Git blob this chunk was extracted from. A re-ingest replaces every
    /// chunk, so this is really a diagnostic: a value that disagrees with the
    /// document's own blob means chunks outlived the revision that produced
    /// them, and search is answering from content the repository no longer has.
    /// </summary>
    public required string SourceBlobSha { get; set; }

    /// <summary>
    /// Embedding of <see cref="Text"/>. The dimension is fixed by the schema
    /// (see <c>EmbeddingDimensions</c>) — changing embedding provider to one
    /// with a different width needs a migration and a full re-index, which is
    /// why the API validates the configured provider against it at startup.
    /// </summary>
    public required Vector Embedding { get; set; }

    /// <summary>
    /// Generated by Postgres from <see cref="Text"/>; never assigned in code.
    /// Backs the keyword half of hybrid search.
    /// </summary>
    public NpgsqlTsVector? SearchVector { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public Document? Document { get; set; }
}
